package com.example.metadata

import android.content.Context
import android.content.IntentSender
import android.net.Uri
import android.os.Build
import android.util.Log
import com.example.data.AppDatabase
import com.example.data.TrackDao
import com.example.model.MetadataWriteState
import com.example.model.Track
import com.example.storage.SafStorageManager
import com.example.storage.StorageWritePermissionHelper
import kotlin.coroutines.coroutineContext
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Semaphore
import kotlinx.coroutines.sync.withPermit
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.io.File
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger

/**
 * Real-time operational phase during bulk metadata push.
 */
enum class PushMetadataPhase(val label: String) {
    READING_PHYSICAL("Reading physical tags"),
    COMPARING("Comparing metadata"),
    WRITING_TAGS("Writing tags to file"),
    VERIFYING("Verifying written metadata"),
    AWAITING_PERMISSION("Awaiting storage permission"),
    DONE_SYNCED("Done / Skipped (already in sync)"),
    DONE_WRITTEN("Done (written to file)"),
    DONE_PARTIAL("Done (partially written)"),
    SKIPPED("Skipped"),
    UNSUPPORTED("Unsupported format"),
    FAILED("Failed")
}

/**
 * Real-time progress feedback during bulk metadata push.
 */
data class PushMetadataProgress(
    val current: Int = 0,
    val total: Int = 0,
    val trackTitle: String = "",
    val trackArtist: String = "",
    val fileName: String = "",
    val phase: PushMetadataPhase = PushMetadataPhase.READING_PHYSICAL,
    val writtenCount: Int = 0,
    val syncedCount: Int = 0,
    val failedCount: Int = 0,
    val partialCount: Int = 0,
    val skippedCount: Int = 0,
    val unsupportedCount: Int = 0,
    val permissionRequiredCount: Int = 0,
    val libraryOnlyCount: Int = 0
)

/**
 * Detail of a failure during bulk metadata push.
 */
data class PushMetadataFailure(
    val trackId: String,
    val title: String,
    val artist: String,
    val filePath: String,
    val reason: String,
    val category: String = "Failed"
)

/**
 * Pending Scoped Storage write permission request for the UI layer to fulfill.
 */
data class PendingWritePermissionRequest(
    val id: String = java.util.UUID.randomUUID().toString(),
    val intentSender: IntentSender,
    val uris: List<Uri>,
    val deferred: CompletableDeferred<Boolean>
)

/**
 * Pending SAF Directory Tree permission request for the UI layer to fulfill.
 */
data class PendingFolderPermissionRequest(
    val id: String = java.util.UUID.randomUUID().toString(),
    val folderPath: String,
    val folderDisplayName: String,
    val affectedTrackCount: Int,
    val deferred: CompletableDeferred<Uri?>
)

/**
 * Comprehensive summary report generated after Push Metadata to Files completes.
 */
data class PushMetadataReport(
    val totalExamined: Int = 0,
    val successfullyWritten: Int = 0,
    val alreadySynchronized: Int = 0,
    val failed: Int = 0,
    val failureReasons: List<PushMetadataFailure> = emptyList(),
    val partial: Int = 0,
    val skipped: Int = 0,
    val unsupported: Int = 0,
    val permissionRequired: Int = 0,
    val libraryOnly: Int = 0,
    val wasCancelled: Boolean = false
)

/**
 * Report generated by library embedded metadata repair/migration.
 */
data class LibraryMigrationReport(
    val totalExamined: Int = 0,
    val successfullyWritten: Int = 0,
    val alreadySynchronized: Int = 0,
    val failed: Int = 0,
    val skippedReadOnlyOrUnsupported: Int = 0
)

/**
 * Background writer queue with controlled concurrency (1-2 concurrent jobs).
 *
 * Ensures audio file tag writing never blocks the main UI or causes audio stuttering,
 * performs read-back verification for every write, updates persistent track status in Room DB,
 * and provides library migration/repair utilities.
 */
class MetadataFileWriteQueue private constructor(
    private val context: Context,
    private val injectedTrackDao: TrackDao? = null,
    private val injectedFileWriter: MetadataFileWriter? = null
) {

    companion object {
        private const val TAG = "MetadataFileWriteQueue"
        private const val MAX_CONCURRENT_WRITES = 2

        @Volatile
        private var INSTANCE: MetadataFileWriteQueue? = null

        fun getInstance(context: Context): MetadataFileWriteQueue {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: MetadataFileWriteQueue(context.applicationContext).also { INSTANCE = it }
            }
        }

        fun createForTesting(
            context: Context,
            trackDao: TrackDao,
            fileWriter: MetadataFileWriter? = null
        ): MetadataFileWriteQueue {
            return MetadataFileWriteQueue(context, trackDao, fileWriter)
        }

        @androidx.annotation.VisibleForTesting
        fun setInstanceForTesting(queue: MetadataFileWriteQueue?) {
            INSTANCE = queue
        }
    }

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val semaphore = Semaphore(MAX_CONCURRENT_WRITES)
    private val trackDao: TrackDao? = injectedTrackDao ?: try {
        AppDatabase.getDatabase(context).trackDao()
    } catch (_: Throwable) {
        null
    }
    private val fileWriter = injectedFileWriter ?: MetadataFileWriter(context, trackDao)

    // Tracks currently undergoing writing, prevents concurrent writes to the same audio file
    private val activeWritingFiles = ConcurrentHashMap.newKeySet<String>()

    private val activeCount = AtomicInteger(0)
    private val _isWriting = MutableStateFlow(false)
    val isWriting: StateFlow<Boolean> = _isWriting.asStateFlow()

    private val _activeWritesCount = MutableStateFlow(0)
    val activeWritesCount: StateFlow<Int> = _activeWritesCount.asStateFlow()

    private val _lastMigrationReport = MutableStateFlow<LibraryMigrationReport?>(null)
    val lastMigrationReport: StateFlow<LibraryMigrationReport?> = _lastMigrationReport.asStateFlow()

    private val _isPushingMetadata = MutableStateFlow(false)
    val isPushingMetadata: StateFlow<Boolean> = _isPushingMetadata.asStateFlow()

    private val _pushProgress = MutableStateFlow<PushMetadataProgress?>(null)
    val pushProgress: StateFlow<PushMetadataProgress?> = _pushProgress.asStateFlow()

    private val _lastPushReport = MutableStateFlow<PushMetadataReport?>(null)
    val lastPushReport: StateFlow<PushMetadataReport?> = _lastPushReport.asStateFlow()

    private val _pendingPermissionRequest = MutableStateFlow<PendingWritePermissionRequest?>(null)
    val pendingPermissionRequest: StateFlow<PendingWritePermissionRequest?> = _pendingPermissionRequest.asStateFlow()

    private val _pendingFolderPermissionRequest = MutableStateFlow<PendingFolderPermissionRequest?>(null)
    val pendingFolderPermissionRequest: StateFlow<PendingFolderPermissionRequest?> = _pendingFolderPermissionRequest.asStateFlow()

    @Volatile
    private var isCancelRequested = false
    private var pushJob: Job? = null

    /**
     * Responds to an external ActivityResult user approval/denial for storage write permission.
     */
    fun onWritePermissionResult(granted: Boolean) {
        Log.i(TAG, "Storage write permission result received: granted=$granted")
        val pending = _pendingPermissionRequest.value
        _pendingPermissionRequest.value = null
        pending?.deferred?.complete(granted)
    }

    /**
     * Responds to an external ActivityResult user selection for SAF folder permission.
     */
    fun onFolderPermissionResult(treeUri: Uri?) {
        Log.i(TAG, "SAF folder permission result received: $treeUri")
        val pending = _pendingFolderPermissionRequest.value
        _pendingFolderPermissionRequest.value = null
        if (treeUri != null) {
            SafStorageManager.takePersistablePermissions(context, treeUri)
        }
        pending?.deferred?.complete(treeUri)
    }

    /**
     * Pauses the queue worker until the user grants or denies folder access via system SAF picker.
     */
    private suspend fun requestFolderPermission(
        folderPath: String,
        folderDisplayName: String,
        trackCount: Int
    ): Uri? {
        val deferred = CompletableDeferred<Uri?>()
        _pendingFolderPermissionRequest.value = PendingFolderPermissionRequest(
            folderPath = folderPath,
            folderDisplayName = folderDisplayName,
            affectedTrackCount = trackCount,
            deferred = deferred
        )
        return try {
            withTimeoutOrNull(90_000) {
                deferred.await()
            }
        } catch (e: CancellationException) {
            _pendingFolderPermissionRequest.value = null
            null
        } finally {
            if (_pendingFolderPermissionRequest.value?.deferred == deferred) {
                _pendingFolderPermissionRequest.value = null
            }
        }
    }

    /**
     * Pauses the queue worker until the user grants or denies write access via system dialogue.
     */
    suspend fun requestWritePermission(intentSender: IntentSender, uris: List<Uri>): Boolean {
        val deferred = CompletableDeferred<Boolean>()
        _pendingPermissionRequest.value = PendingWritePermissionRequest(
            intentSender = intentSender,
            uris = uris,
            deferred = deferred
        )
        return try {
            withTimeoutOrNull(60_000) {
                deferred.await()
            } ?: false
        } catch (e: CancellationException) {
            _pendingPermissionRequest.value = null
            false
        } finally {
            if (_pendingPermissionRequest.value?.deferred == deferred) {
                _pendingPermissionRequest.value = null
            }
        }
    }

    fun cancelPushMetadata() {
        Log.i(TAG, "User requested cancellation of bulk metadata push.")
        isCancelRequested = true
        _pendingPermissionRequest.value?.deferred?.complete(false)
        _pendingPermissionRequest.value = null
        _pendingFolderPermissionRequest.value?.deferred?.complete(null)
        _pendingFolderPermissionRequest.value = null
        pushJob?.cancel()
        _isPushingMetadata.value = false
    }

    /**
     * Queues an asynchronous file metadata write with controlled concurrency.
     * Updates track status in DB to WRITING_TO_FILE immediately.
     */
    fun enqueue(
        track: Track,
        artworkBytes: ByteArray? = null,
        artworkMimeType: String = "image/jpeg",
        onComplete: ((MetadataWriteResult) -> Unit)? = null
    ): Job {
        return scope.launch {
            if (track.id.isNotBlank()) {
                try {
                    trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.WRITING_TO_FILE.name)
                } catch (_: Exception) {}
            }

            val pathKey = track.filePath.ifBlank { track.id }
            var lockAcquired = false
            try {
                while (!activeWritingFiles.add(pathKey)) {
                    delay(50)
                }
                lockAcquired = true

                activeCount.incrementAndGet()
                _activeWritesCount.value = activeCount.get()
                _isWriting.value = true

                var currentTrack = track
                val dbTrack = trackDao?.getTrackById(track.id)
                if (dbTrack != null && dbTrack.analysisState != "ANALYSING") {
                    currentTrack = dbTrack.toTrack()
                }

                val result = semaphore.withPermit {
                    fileWriter.writeAsync(currentTrack, artworkBytes, artworkMimeType)
                }

                onComplete?.invoke(result)
            } finally {
                if (lockAcquired) {
                    activeWritingFiles.remove(pathKey)
                    val current = activeCount.decrementAndGet().coerceAtLeast(0)
                    _activeWritesCount.value = current
                    if (current <= 0) {
                        _isWriting.value = false
                    }
                }
            }
        }
    }

    /**
     * Synchronous / suspend write for situations requiring immediate completion.
     * Interactively requests Scoped Storage MediaStore write permission if required.
     */
    suspend fun writeDirect(
        track: Track,
        artworkBytes: ByteArray? = null,
        artworkMimeType: String = "image/jpeg"
    ): MetadataWriteResult {
        val pathKey = track.filePath.ifBlank { track.id }
        var lockAcquired = false
        return try {
            while (!activeWritingFiles.add(pathKey)) {
                delay(50)
            }
            lockAcquired = true

            if (artworkBytes != null && artworkBytes.isNotEmpty()) {
                Log.i(TAG, "ARTWORK_WRITE_STARTED: Writing embedded artwork (${artworkBytes.size} bytes) to ${track.filePath} for track ${track.id}")
            }

            var result = semaphore.withPermit {
                fileWriter.writeAsync(track, artworkBytes, artworkMimeType)
            }

            // If permission required and IntentSender provided, prompt user and retry once
            if (result is MetadataWriteResult.PermissionRequired && result.intentSender != null) {
                val targetUri = result.uri ?: StorageWritePermissionHelper.resolveTargetUri(context, track)
                if (targetUri != null) {
                    Log.i(TAG, "MEDIASTORE_WRITE_PERMISSION_REQUESTED: Requesting write permission for $targetUri (track ${track.id})")
                    val granted = requestWritePermission(result.intentSender, listOf(targetUri))
                    if (granted) {
                        Log.i(TAG, "MEDIASTORE_WRITE_PERMISSION_GRANTED: Permission granted for $targetUri (track ${track.id})")
                        result = semaphore.withPermit {
                            fileWriter.writeAsync(track, artworkBytes, artworkMimeType)
                        }
                    } else {
                        Log.w(TAG, "MediaStore write permission denied for $targetUri")
                        Log.e(TAG, "ARTWORK_WRITE_FAILED: MediaStore permission denied for track ${track.id}")
                    }
                }
            }

            when (result) {
                is MetadataWriteResult.Written,
                is MetadataWriteResult.AlreadyInSync,
                is MetadataWriteResult.Partial -> {
                    if (artworkBytes != null && artworkBytes.isNotEmpty()) {
                        Log.i(TAG, "ARTWORK_WRITE_SUCCESS: Successfully wrote and verified embedded artwork for track ${track.id}")
                        com.example.util.AlbumArtHelper.invalidateTrack(track.id, track.artist, track.album)
                        com.example.metadata.ArtworkCache(context).evictArtworkForTrack(track.id)
                        Log.i(TAG, "ARTWORK_CACHE_INVALIDATED: Evicted cache for track ${track.id}")
                        trackDao?.updateMetadataWriteState(track.id, com.example.model.MetadataWriteState.ARTWORK_SAVED.name)
                        Log.i(TAG, "TRACK_METADATA_REFRESHED: Updated database state to ARTWORK_SAVED for track ${track.id}")
                    }
                    if (track.filePath.isNotBlank() && !track.filePath.startsWith("content://")) {
                        try {
                            android.media.MediaScannerConnection.scanFile(context, arrayOf(track.filePath), null, null)
                        } catch (_: Throwable) {}
                    }
                }
                is MetadataWriteResult.PermissionRequired -> {
                    Log.w(TAG, "ARTWORK_WRITE_FAILED: Storage write permission required for track ${track.id}")
                    trackDao?.updateMetadataWriteState(track.id, com.example.model.MetadataWriteState.PERMISSION_REQUIRED.name)
                }
                is MetadataWriteResult.Unsupported -> {
                    Log.w(TAG, "ARTWORK_WRITE_FAILED: Format unsupported for track ${track.id}: ${result.reason}")
                    trackDao?.updateMetadataWriteState(track.id, com.example.model.MetadataWriteState.FORMAT_WRITE_UNSUPPORTED.name)
                }
                is MetadataWriteResult.Failed -> {
                    Log.e(TAG, "ARTWORK_WRITE_FAILED: Tag write failed for track ${track.id}: ${result.reason}")
                    trackDao?.updateMetadataWriteState(track.id, com.example.model.MetadataWriteState.FILE_WRITE_FAILED.name)
                }
                else -> {
                    if (artworkBytes != null && artworkBytes.isNotEmpty()) {
                        Log.w(TAG, "ARTWORK_WRITE_FAILED: Unexpected result $result for track ${track.id}")
                    }
                }
            }

            result
        } finally {
            if (lockAcquired) {
                activeWritingFiles.remove(pathKey)
            }
        }
    }

    /**
     * Scans the database library for tracks whose metadata has not been physically written to disk
     * (or is out of sync), and embeds the latest database metadata into each file.
     *
     * Smart sync: If the file already physically contains all metadata from the database,
     * the track state is marked FILE_WRITE_SUCCESS without an unnecessary file rewrite.
     */
    suspend fun repairOrMigrateLibrary(
        onProgress: ((current: Int, total: Int, trackTitle: String) -> Unit)? = null
    ): LibraryMigrationReport = withContext(Dispatchers.IO) {
        val tracksNeedingWrite = trackDao?.getTracksNeedingFileWrite()?.map { it.toTrack() } ?: emptyList()
        val total = tracksNeedingWrite.size
        var writtenCount = 0
        var syncedCount = 0
        var failedCount = 0
        var skippedCount = 0

        Log.i(TAG, "Starting library embedded metadata migration for $total tracks...")

        for ((index, track) in tracksNeedingWrite.withIndex()) {
            onProgress?.invoke(index + 1, total, track.title)

            val path = track.filePath
            if (path.isBlank() || path.startsWith("demo://") || path.startsWith("http")) {
                skippedCount++
                trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FORMAT_WRITE_UNSUPPORTED.name)
                continue
            }

            val isContentUri = path.startsWith("content://")
            val file = if (!isContentUri) File(path) else null

            val hasDirectWrite = file != null && StorageWritePermissionHelper.isDirectlyWritableFile(file)
            val targetUri = if (!hasDirectWrite) StorageWritePermissionHelper.resolveTargetUri(context, track) else null
            val canWriteTarget = hasDirectWrite || (targetUri != null && StorageWritePermissionHelper.hasUriWritePermission(context, targetUri))

            if (file != null && !file.exists() && targetUri == null) {
                trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FILE_WRITE_FAILED.name)
                failedCount++
                continue
            }

            if (!canWriteTarget && targetUri == null) {
                val state = MetadataWriteState.READ_ONLY_FILE
                trackDao?.updateMetadataWriteState(track.id, state.name)
                skippedCount++
                continue
            }

            // Read physical tags from file
            val readSource = if (hasDirectWrite || file?.canRead() == true) path else (targetUri?.toString() ?: path)
            val physical = AudioEmbeddedMetadataReader.read(context, readSource)

            // Check if physical file is already in sync with database
            val titleMatches = track.title.isBlank() || physical.title.equals(track.title, ignoreCase = true)
            val artistMatches = track.artist.isBlank() || physical.artist.equals(track.artist, ignoreCase = true)
            val albumMatches = track.album.isBlank() || track.album == "Single" || track.album == "Unknown Album" ||
                    physical.album.equals(track.album, ignoreCase = true)
            val bpmMatches = track.bpm <= 0.0 || (physical.bpm != null && kotlin.math.abs(physical.bpm - track.bpm) < 1.0)
            val keyMatches = track.musicalKey.isBlank() || track.musicalKey == "—" || track.musicalKey == "-" ||
                    physical.musicalKey.equals(track.musicalKey, ignoreCase = true)

            val alreadyInSync = titleMatches && artistMatches && albumMatches && bpmMatches && keyMatches

            if (alreadyInSync && (physical.title != null || physical.artist != null)) {
                // File already has the tags! Mark as embedded
                trackDao?.updateMetadataWriteState(track.id, MetadataWriteState.FILE_WRITE_SUCCESS.name)
                syncedCount++
            } else {
                // Need to embed metadata into file
                val writeRes = semaphore.withPermit {
                    fileWriter.writeAsync(track)
                }
                when (writeRes) {
                    is MetadataWriteResult.Written,
                    is MetadataWriteResult.TextWritten,
                    is MetadataWriteResult.ArtworkEmbedded -> writtenCount++
                    is MetadataWriteResult.Partial,
                    is MetadataWriteResult.ArtworkWriteFailed -> writtenCount++
                    is MetadataWriteResult.AlreadyInSync -> syncedCount++
                    is MetadataWriteResult.Skipped, is MetadataWriteResult.ReadOnlyFile,
                    is MetadataWriteResult.Unsupported, is MetadataWriteResult.PermissionRequired,
                    is MetadataWriteResult.LibraryOnly -> skippedCount++
                    is MetadataWriteResult.Failed, is MetadataWriteResult.VerificationFailed -> failedCount++
                }
            }
        }

        val report = LibraryMigrationReport(
            totalExamined = total,
            successfullyWritten = writtenCount,
            alreadySynchronized = syncedCount,
            failed = failedCount,
            skippedReadOnlyOrUnsupported = skippedCount
        )
        _lastMigrationReport.value = report
        Log.i(TAG, "Completed library embedded metadata migration: $report")
        report
    }

    /**
     * Determines and pre-requests storage permissions in bulk before queue processing.
     * Never prompts the user inside the per-track processing loop.
     *
     * 1. Detects tracks in folders requiring one-time SAF directory tree access.
     * 2. Detects MediaStore URIs requiring batch write approval (Android 11+ / API 30+).
     */
    /**
     * Determines and pre-requests storage permissions in bulk before queue or batch processing.
     * Never prompts the user inside the per-track processing loop.
     *
     * 1. Detects tracks in folders requiring one-time SAF directory tree access.
     * 2. Detects MediaStore URIs requiring batch write approval (Android 11+ / API 30+).
     * 3. Skips any tracks or folders that are already writable or previously authorized.
     */
    suspend fun ensurePermissionsUpfront(
        tracks: List<Track>,
        total: Int = tracks.size,
        onProgress: ((PushMetadataProgress) -> Unit)? = null
    ): Boolean {
        if (isCancelRequested || !coroutineContext.isActive) return false

        val mediaStoreUrisNeedingPerm = mutableListOf<Uri>()
        val tracksNeedingFolderPerm = mutableListOf<Track>()

        for (track in tracks) {
            val path = track.filePath
            if (path.isBlank() || path.startsWith("demo://") || path.startsWith("http")) continue

            val canonical = StorageWritePermissionHelper.resolveCanonicalStorage(context, track, trackDao)
            if (canonical == null) continue

            if (canonical.isWritable) continue

            if (canonical.uri.scheme == "content") {
                if (canonical.uri.authority?.contains("media") == true) {
                    if (!StorageWritePermissionHelper.hasUriWritePermission(context, canonical.uri)) {
                        mediaStoreUrisNeedingPerm.add(canonical.uri)
                    }
                } else {
                    tracksNeedingFolderPerm.add(track)
                }
            } else {
                val mediaUri = StorageWritePermissionHelper.resolveTargetUri(context, track)
                if (mediaUri != null && mediaUri.authority?.contains("media") == true) {
                    if (!StorageWritePermissionHelper.hasUriWritePermission(context, mediaUri)) {
                        mediaStoreUrisNeedingPerm.add(mediaUri)
                    }
                } else {
                    tracksNeedingFolderPerm.add(track)
                }
            }
        }

        var allGranted = true

        // 1. SAF Folder Permission upfront if any tracks are in non-permitted folders
        if (tracksNeedingFolderPerm.isNotEmpty() && !isCancelRequested && coroutineContext.isActive) {
            val foldersGrouped = tracksNeedingFolderPerm.groupBy {
                File(it.filePath).parentFile?.absolutePath ?: ""
            }.filterKeys { it.isNotBlank() }

            val persistedFolders = SafStorageManager.getPersistedWriteFolderUris(context)

            for ((folderPath, folderTracks) in foldersGrouped) {
                if (isCancelRequested || !coroutineContext.isActive) {
                    allGranted = false
                    break
                }
                val sampleTrack = folderTracks.firstOrNull() ?: continue
                val existingDoc = SafStorageManager.findDocumentForTrack(context, sampleTrack)
                if (existingDoc != null && existingDoc.canWrite()) {
                    continue
                }

                val primaryFolder = File(folderPath)
                val initProgress = PushMetadataProgress(
                    current = 0,
                    total = total,
                    phase = PushMetadataPhase.AWAITING_PERMISSION,
                    trackTitle = "Storage Permission Required",
                    fileName = "Requesting folder permission for '${primaryFolder.name}' (${folderTracks.size} files)..."
                )
                _pushProgress.value = initProgress
                onProgress?.invoke(initProgress)

                val grantedTreeUri = requestFolderPermission(
                    folderPath = primaryFolder.absolutePath,
                    folderDisplayName = primaryFolder.name.ifBlank { "Music Folder" },
                    trackCount = folderTracks.size
                )
                if (grantedTreeUri != null) {
                    SafStorageManager.takePersistablePermissions(context, grantedTreeUri)
                    Log.i(TAG, "User granted and persisted SAF folder permission for $grantedTreeUri")
                } else {
                    Log.w(TAG, "User dismissed SAF folder permission for ${primaryFolder.name}. Affected tracks will be saved to library only.")
                    allGranted = false
                }
            }
        }

        // 2. MediaStore Batch Write Permission (Android 11+ / API 30+)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && mediaStoreUrisNeedingPerm.isNotEmpty() && !isCancelRequested && coroutineContext.isActive) {
            val distinctUris = mediaStoreUrisNeedingPerm.distinct().filter { uri ->
                !StorageWritePermissionHelper.hasUriWritePermission(context, uri)
            }
            val batches = distinctUris.chunked(150)
            for (batch in batches) {
                if (isCancelRequested || !coroutineContext.isActive) {
                    allGranted = false
                    break
                }
                val intentSender = StorageWritePermissionHelper.createBatchWriteRequest(context, batch)
                if (intentSender != null) {
                    val initProgress = PushMetadataProgress(
                        current = 0,
                        total = total,
                        phase = PushMetadataPhase.AWAITING_PERMISSION,
                        trackTitle = "Storage Permission Required",
                        fileName = "Requesting batch permission to modify ${batch.size} audio files..."
                    )
                    _pushProgress.value = initProgress
                    onProgress?.invoke(initProgress)

                    val granted = requestWritePermission(intentSender, batch)
                    Log.i(TAG, "Batch write permission result: granted=$granted for ${batch.size} tracks")
                    if (!granted) {
                        Log.w(TAG, "User denied batch write permission. Files will be saved to library only.")
                        allGranted = false
                    }
                }
            }
        }

        return allGranted
    }

    /**
     * Executes the authoritative 12-step bulk "Push Metadata to Files" operation
     * across the entire library:
     * 1. Reads all tracks in the SoundSync library.
     * 2. Reads SoundSync's existing metadata database.
     * 3. Reads actual embedded metadata from every physical file.
     * 4. Compares the two.
     * 5. Determines which fields need writing.
     * 6. Writes SoundSync metadata into the physical audio file (dual INFO + id3 on WAV, ID3v2.3, Vorbis, etc.).
     * 7. Closes the writer.
     * 8. Reopens the physical file.
     * 9. Reads the tags back.
     * 10. Verifies that they were actually written.
     * 11. Updates the track status in Room DB.
     * 12. Continues to the next track.
     */
    suspend fun pushMetadataToFiles(
        forceAll: Boolean = true,
        onProgress: ((PushMetadataProgress) -> Unit)? = null
    ): PushMetadataReport = withContext(Dispatchers.IO) {
        pushJob = coroutineContext[Job]
        isCancelRequested = false
        _isPushingMetadata.value = true

        val allTracks = trackDao?.getAllTracksList()?.map { it.toTrack() } ?: emptyList()
        val total = allTracks.size

        var writtenCount = 0
        var syncedCount = 0
        var partialCount = 0
        var skippedCount = 0
        var unsupportedCount = 0
        var permissionRequiredCount = 0
        var libraryOnlyCount = 0
        var failedCount = 0
        val failures = mutableListOf<PushMetadataFailure>()
        var tracksProcessed = 0

        try {
            ensurePermissionsUpfront(allTracks, total, onProgress)

            for ((index, track) in allTracks.withIndex()) {
                if (isCancelRequested || !coroutineContext.isActive) {
                    Log.i(TAG, "Push metadata loop exiting due to cancellation.")
                    break
                }
                tracksProcessed = index + 1
                val current = tracksProcessed
                val fileName = File(track.filePath).name.ifBlank { track.filePath }

                val updateProgress = { phase: PushMetadataPhase ->
                    val p = PushMetadataProgress(
                        current = current,
                        total = total,
                        trackTitle = track.title.ifBlank { fileName },
                        trackArtist = track.artist.ifBlank { "Unknown Artist" },
                        fileName = fileName,
                        phase = phase,
                        writtenCount = writtenCount,
                        syncedCount = syncedCount,
                        failedCount = failedCount,
                        partialCount = partialCount,
                        skippedCount = skippedCount,
                        unsupportedCount = unsupportedCount,
                        permissionRequiredCount = permissionRequiredCount,
                        libraryOnlyCount = libraryOnlyCount
                    )
                    _pushProgress.value = p
                    onProgress?.invoke(p)
                }

                // Step 3: Read actual embedded metadata from physical file
                updateProgress(PushMetadataPhase.READING_PHYSICAL)
                val path = track.filePath
                if (path.isBlank() || path.startsWith("demo://") || path.startsWith("http")) {
                    syncedCount++
                    updateProgress(PushMetadataPhase.DONE_SYNCED)
                    continue
                }

                // Acquire per-file lock to prevent concurrent writes to the same audio file
                val pathKey = track.filePath.ifBlank { track.id }
                var fileLockAcquired = false
                while (!activeWritingFiles.add(pathKey)) {
                    delay(50)
                    if (isCancelRequested || !coroutineContext.isActive) break
                }
                if (isCancelRequested || !coroutineContext.isActive) break
                fileLockAcquired = true

                try {
                    // Prevent race condition with TrackAnalysisManager
                    var currentTrack = track
                    var waitAttempts = 0
                    while (waitAttempts < 10) {
                        val dbTrack = trackDao?.getTrackById(currentTrack.id)
                        if (dbTrack != null && dbTrack.analysisState == "ANALYSING") {
                            delay(200)
                            waitAttempts++
                            currentTrack = dbTrack.toTrack()
                        } else {
                            if (dbTrack != null) {
                                currentTrack = dbTrack.toTrack()
                            }
                            break
                        }
                    }

                    val targetUri = StorageWritePermissionHelper.resolveTargetUri(context, currentTrack)
                    val readSource = if (File(path).exists()) path else (targetUri?.toString() ?: path)
                    val physical = AudioEmbeddedMetadataReader.read(context, readSource)

                    // Step 4 & 5: Compare the two & determine which fields need writing
                    updateProgress(PushMetadataPhase.COMPARING)

                    val titleNeedsWrite = currentTrack.title.isNotBlank() &&
                            currentTrack.title != "Unknown Title" &&
                            !currentTrack.title.equals(physical.title, ignoreCase = true)

                    val artistNeedsWrite = currentTrack.artist.isNotBlank() &&
                            currentTrack.artist != "Unknown Artist" &&
                            !currentTrack.artist.equals(physical.artist, ignoreCase = true)

                    val albumNeedsWrite = currentTrack.album.isNotBlank() &&
                            currentTrack.album != "Single" &&
                            currentTrack.album != "Unknown Album" &&
                            !currentTrack.album.equals(physical.album, ignoreCase = true)

                    val genreNeedsWrite = currentTrack.genre.isNotBlank() &&
                            currentTrack.genre != "DJ Library" &&
                            currentTrack.genre != "Club" &&
                            currentTrack.genre != "Unknown Genre" &&
                            !currentTrack.genre.equals(physical.genre, ignoreCase = true)

                    val yearNeedsWrite = currentTrack.releaseYear != null &&
                            currentTrack.releaseYear > 0 &&
                            currentTrack.releaseYear != physical.releaseYear

                    val bpmNeedsWrite = currentTrack.bpm > 0.0 &&
                            (physical.bpm == null || kotlin.math.abs(physical.bpm - currentTrack.bpm) > 1.0)

                    val keyNeedsWrite = currentTrack.musicalKey.isNotBlank() &&
                            currentTrack.musicalKey != "—" &&
                            currentTrack.musicalKey != "-" &&
                            !currentTrack.musicalKey.equals(physical.musicalKey, ignoreCase = true)

                    val trackNumberNeedsWrite = currentTrack.trackNumber > 0 &&
                            currentTrack.trackNumber != physical.trackNumber

                    val hasDbArtwork = !currentTrack.artworkCachePath.isNullOrBlank() || !currentTrack.artworkUrl.isNullOrBlank()
                    val artworkNeedsWrite = hasDbArtwork && (!physical.hasEmbeddedArtwork || physical.embeddedArtworkSize <= 0)

                    val hasAnyDifference = titleNeedsWrite || artistNeedsWrite || albumNeedsWrite ||
                            genreNeedsWrite || yearNeedsWrite || bpmNeedsWrite || keyNeedsWrite ||
                            trackNumberNeedsWrite || artworkNeedsWrite

                    val hasPhysicalTags = physical.title != null || physical.artist != null || physical.bpm != null

                    if (!hasAnyDifference && hasPhysicalTags && !forceAll) {
                        syncedCount++
                        trackDao?.updateMetadataWriteState(currentTrack.id, MetadataWriteState.FILE_WRITE_SUCCESS.name)
                        updateProgress(PushMetadataPhase.DONE_SYNCED)
                        continue
                    }

                    if (!hasAnyDifference && hasPhysicalTags) {
                        syncedCount++
                        trackDao?.updateMetadataWriteState(currentTrack.id, MetadataWriteState.FILE_WRITE_SUCCESS.name)
                        updateProgress(PushMetadataPhase.DONE_SYNCED)
                        continue
                    }

                    // Step 6: Write SoundSync metadata into physical audio file
                    updateProgress(PushMetadataPhase.WRITING_TAGS)

                    val activeArtworkBytes = currentTrack.artworkCachePath?.let { cachePath ->
                        try {
                            val f = File(cachePath)
                            if (f.exists() && f.canRead()) f.readBytes() else null
                        } catch (_: Exception) { null }
                    }

                    val writeResult = semaphore.withPermit {
                        fileWriter.writeAsync(currentTrack, activeArtworkBytes)
                    }

                    // Step 7-10: Reader verification is performed inside fileWriter.writeAsync
                    updateProgress(PushMetadataPhase.VERIFYING)

                    // Step 11: Update track status
                    when (writeResult) {
                        is MetadataWriteResult.Written,
                        is MetadataWriteResult.TextWritten,
                        is MetadataWriteResult.ArtworkEmbedded -> {
                            writtenCount++
                            updateProgress(PushMetadataPhase.DONE_WRITTEN)
                        }
                        is MetadataWriteResult.ArtworkWriteFailed -> {
                            partialCount++
                            failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, writeResult.reason, category = "Artwork Embedding"))
                            updateProgress(PushMetadataPhase.DONE_PARTIAL)
                        }
                        is MetadataWriteResult.AlreadyInSync -> {
                            syncedCount++
                            updateProgress(PushMetadataPhase.DONE_SYNCED)
                        }
                        is MetadataWriteResult.Partial -> {
                            partialCount++
                            writtenCount++
                            updateProgress(PushMetadataPhase.DONE_PARTIAL)
                        }
                        is MetadataWriteResult.LibraryOnly -> {
                            libraryOnlyCount++
                            failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, writeResult.reason, category = "Updated - Library Only"))
                            updateProgress(PushMetadataPhase.SKIPPED)
                        }
                        is MetadataWriteResult.Skipped -> {
                            libraryOnlyCount++
                            failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, writeResult.reason, category = "Updated - Library Only"))
                            updateProgress(PushMetadataPhase.SKIPPED)
                        }
                        is MetadataWriteResult.ReadOnlyFile -> {
                            libraryOnlyCount++
                            failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, "File is read-only on device storage; saved to SoundSync library", category = "Updated - Library Only"))
                            updateProgress(PushMetadataPhase.SKIPPED)
                        }
                        is MetadataWriteResult.PermissionRequired -> {
                            permissionRequiredCount++
                            failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, "Permission required to access file or content URI: ${writeResult.reason}", category = "Permission"))
                            updateProgress(PushMetadataPhase.SKIPPED)
                        }
                        is MetadataWriteResult.Unsupported -> {
                            unsupportedCount++
                            libraryOnlyCount++
                            failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, "Format not supported for tag writing (${writeResult.reason}); saved to SoundSync library", category = "Updated - Library Only"))
                            updateProgress(PushMetadataPhase.SKIPPED)
                        }
                        is MetadataWriteResult.VerificationFailed -> {
                            failedCount++
                            failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, "Verification failed for ${writeResult.field}: expected '${writeResult.expected}', got '${writeResult.actual}'", category = "Verification"))
                            updateProgress(PushMetadataPhase.FAILED)
                        }
                        is MetadataWriteResult.Failed -> {
                            val hasDbMetadata = currentTrack.isAppleIdentified ||
                                    (currentTrack.title.isNotBlank() && currentTrack.title != "Unknown Title" && currentTrack.artist.isNotBlank() && currentTrack.artist != "Unknown Artist")
                            if (hasDbMetadata) {
                                libraryOnlyCount++
                                failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, "${writeResult.reason}; saved to SoundSync library", category = "Updated - Library Only"))
                                updateProgress(PushMetadataPhase.SKIPPED)
                            } else {
                                failedCount++
                                failures.add(PushMetadataFailure(currentTrack.id, currentTrack.title, currentTrack.artist, path, writeResult.reason, category = "Failed"))
                                updateProgress(PushMetadataPhase.FAILED)
                            }
                        }
                    }
                    // Step 12: Continue to next track
                } finally {
                    if (fileLockAcquired) {
                        activeWritingFiles.remove(pathKey)
                    }
                }
            }
        } catch (e: CancellationException) {
            Log.i(TAG, "Push metadata to files was cancelled by user.")
        } finally {
            _isPushingMetadata.value = false
        }

        val wasCancelled = isCancelRequested || !coroutineContext.isActive
        val report = PushMetadataReport(
            totalExamined = tracksProcessed,
            successfullyWritten = writtenCount,
            alreadySynchronized = syncedCount,
            failed = failedCount,
            failureReasons = failures,
            partial = partialCount,
            skipped = skippedCount,
            unsupported = unsupportedCount,
            permissionRequired = permissionRequiredCount,
            libraryOnly = libraryOnlyCount,
            wasCancelled = wasCancelled
        )
        _lastPushReport.value = report
        Log.i(TAG, "Push metadata to files completed (wasCancelled=$wasCancelled): $report")
        report
    }

    /**
     * Retries writing previously failed or database-only tracks using already-discovered
     * metadata stored in the Room database, WITHOUT making redundant internet queries.
     */
    suspend fun retryFailedTracks(
        onProgress: ((PushMetadataProgress) -> Unit)? = null
    ): PushMetadataReport = withContext(Dispatchers.IO) {
        val failedEntities = trackDao?.getTracksWithWriteIssues() ?: emptyList()
        val failedTracks = failedEntities.map { it.toTrack() }
        val total = failedTracks.size

        var writtenCount = 0
        var syncedCount = 0
        var partialCount = 0
        var libraryOnlyCount = 0
        var failedCount = 0
        var permissionRequiredCount = 0
        val failures = mutableListOf<PushMetadataFailure>()

        Log.i(TAG, "Retrying file writes for $total tracks using existing database metadata...")

        ensurePermissionsUpfront(failedTracks, total, onProgress)

        for ((index, track) in failedTracks.withIndex()) {
            if (isCancelRequested || !coroutineContext.isActive) break

            val current = index + 1
            val fileName = File(track.filePath).name.ifBlank { track.filePath }

            val p = PushMetadataProgress(
                current = current,
                total = total,
                trackTitle = track.title.ifBlank { fileName },
                trackArtist = track.artist.ifBlank { "Unknown Artist" },
                fileName = fileName,
                phase = PushMetadataPhase.WRITING_TAGS,
                writtenCount = writtenCount,
                syncedCount = syncedCount,
                failedCount = failedCount,
                partialCount = partialCount,
                libraryOnlyCount = libraryOnlyCount
            )
            _pushProgress.value = p
            onProgress?.invoke(p)

            val activeArtworkBytes = track.artworkCachePath?.let { cachePath ->
                try {
                    val f = File(cachePath)
                    if (f.exists() && f.canRead()) f.readBytes() else null
                } catch (_: Exception) { null }
            }

            val writeResult = semaphore.withPermit {
                fileWriter.writeAsync(track, activeArtworkBytes)
            }

            when (writeResult) {
                is MetadataWriteResult.Written,
                is MetadataWriteResult.TextWritten,
                is MetadataWriteResult.ArtworkEmbedded -> writtenCount++
                is MetadataWriteResult.ArtworkWriteFailed -> {
                    partialCount++
                    failures.add(PushMetadataFailure(track.id, track.title, track.artist, track.filePath, writeResult.reason, category = "Artwork Embedding"))
                }
                is MetadataWriteResult.AlreadyInSync -> syncedCount++
                is MetadataWriteResult.Partial -> {
                    partialCount++
                    writtenCount++
                }
                is MetadataWriteResult.LibraryOnly -> {
                    libraryOnlyCount++
                    failures.add(PushMetadataFailure(track.id, track.title, track.artist, track.filePath, writeResult.reason, category = "Updated - Library Only"))
                }
                is MetadataWriteResult.ReadOnlyFile -> {
                    libraryOnlyCount++
                    failures.add(PushMetadataFailure(track.id, track.title, track.artist, track.filePath, "Storage permission denied: File is read-only", category = "Updated - Library Only"))
                }
                is MetadataWriteResult.PermissionRequired -> {
                    permissionRequiredCount++
                    failures.add(PushMetadataFailure(track.id, track.title, track.artist, track.filePath, "Storage permission denied: ${writeResult.reason}", category = "Permission"))
                }
                is MetadataWriteResult.Unsupported -> {
                    libraryOnlyCount++
                    failures.add(PushMetadataFailure(track.id, track.title, track.artist, track.filePath, "Format not supported (${writeResult.reason})", category = "Updated - Library Only"))
                }
                is MetadataWriteResult.VerificationFailed -> {
                    failedCount++
                    failures.add(PushMetadataFailure(track.id, track.title, track.artist, track.filePath, "Verification failed for ${writeResult.field}", category = "Verification"))
                }
                is MetadataWriteResult.Failed -> {
                    failedCount++
                    failures.add(PushMetadataFailure(track.id, track.title, track.artist, track.filePath, writeResult.reason, category = "Failed"))
                }
                is MetadataWriteResult.Skipped -> libraryOnlyCount++
            }
        }

        val report = PushMetadataReport(
            totalExamined = total,
            successfullyWritten = writtenCount,
            alreadySynchronized = syncedCount,
            failed = failedCount,
            failureReasons = failures,
            partial = partialCount,
            permissionRequired = permissionRequiredCount,
            libraryOnly = libraryOnlyCount,
            wasCancelled = isCancelRequested || !coroutineContext.isActive
        )
        _lastPushReport.value = report
        report
    }
}
